version: '3'

services:
  webserver:
    build:
      context: .
    volumes:
      - ${PROJECTS_PATH}:/var/www/html
    ports:
      - "${APACHE_SERVER_PORT}:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
